[lints.clippy]

[package]
name = "asteri"
version = "0.3.1"
edition = "2021"
description = "A compiled, statically typed DSL for game development."
repository = "https://github.com/Censera/asteri"
readme = "README.md"
license = "MIT"
keywords = ["compiler", "language", "llvm"]
categories = ["command-line-utilities", "development-tools::compilers"]

[dependencies]
inkwell = { version = "0.9.0", features = ["llvm20-1"] }

[profile.release]
opt-level = "z"
lto = true
strip = true
codegen-units = 1
panic = "abort"
