[lints.clippy]

[package]
name = "asteri"
version = "0.3.0"
edition = "2021"
description = "A compiled, statically typed DSL for game development."
repository = "https://github.com/Censera/asteri"
readme = "README.md"
license = "MIT"
keywords = ["compiler", "language", "llvm"]
categories = ["command-line-utilities", "development-tools::compilers"]

[dependencies]
inkwell = { version = "0.9.0", features = ["llvm20-1"] }

[target.'cfg(target_os = "linux")'.dependencies]
llvm-sys = { version = "201", features = ["prefer-dynamic"] }

# isnt needed for me
# [profile.dev]
# opt-level = 3
# lto = "fat"
# codegen-units = 1
# debug = true

[profile.release]
opt-level = "z"
lto = true
strip = true
codegen-units = 1
panic = "abort"
