[lints.clippy]

[package]
name = "asteri"
version = "0.3.0"
edition = "2021"

[dependencies]
inkwell = { version = "0.9.0", features = ["llvm20-1"] }

[profile.dev]
opt-level = 3
lto = "fat"
codegen-units = 1
debug = false

[profile.release]
opt-level = "z"
lto = true
strip = true
codegen-units = 1
panic = "abort"
