enum {
  LEFT_PREN, RIGHT_PAREN, LEFT_BRACE, RIGHT_BRACE,
  COMMA, DOT, MINUS, PLUS, SEMICOLON, COLON, SLASH, STAR,

  BANG, BANG_EQUAL,
  EQUAL, EQUAL_EQUAL,
  GREATER, GREATER_EQUAL,
  LESS, LESS_EQUAL,

  CONVERT,

  IDENT, STRING, INR, DECIMAL, BOOLEAN, CHAR, FILE,

  CLASS, ELSE, FALSE, TRUE, FOR, FUN, IF, SWITCH,
  MATCH, EMPTY, OR, PRINT, ERROR, WARN, SORT,
  READ, 
  RETURN, SUPER, THIS, LET, READONLY, OPEN, CLOSE,

  EOF
}
