name: release

on:
  push:
    tags: ['v*']

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable

      - name: Install LLVM for Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y llvm-20-dev lld-20 clang-20
          echo "LLVM_SYS_201_PREFIX=/usr/lib/llvm-20" >> $GITHUB_ENV
          echo "LLVM_LINK_SHARED=1" >> $GITHUB_ENV

      - name: Install LLVM for macOS
        if: runner.os == 'macOS'
        run: |
          brew install llvm@20
          echo "LLVM_SYS_201_PREFIX=$(brew --prefix llvm@20)" >> $GITHUB_ENV
          echo "LLVM_LINK_SHARED=1" >> $GITHUB_ENV

      - name: Build
        run: cargo build --release

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/asteri

