name: test

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable

      - name: Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y llvm-20-dev lld-20 clang-20
          echo "LLVM_SYS_201_PREFIX=/usr/lib/llvm-20" >> $GITHUB_ENV
          echo "LLVM_LINK_SHARED=1" >> $GITHUB_ENV

      - name: macOS
        if: runner.os == 'macOS'
        run: |
          brew install llvm@20
          echo "LLVM_SYS_201_PREFIX=$(brew --prefix llvm@20)" >> $GITHUB_ENV
          echo "LLVM_LINK_SHARED=1" >> $GITHUB_ENV

      - name: getchild
        if: runner.os == 'Windows'
        shell: powershell
        run: |
          Get-ChildItem Env: | Sort-Object Name
      
      - name: z
        if: runner.os == 'Windows'
        shell: powershell
        run: |
          echo "LLVM_SYS_201_PREFIX=C:\Program Files\LLVM" >> $env:GITHUB_ENV

      - name: verify llvm
        if: runner.os == 'Windows'
        shell: powershell
        run: |
          echo $env:LLVM_SYS_201_PREFIX

      - run: cargo build
      - run: cargo test
